### ISSUE TITLE
Manifest entry for main class & dependencies missing in jar

### ISSUE THREAD

**Issue by SvenEwald** [zero11it/acme-client-letsencrypt-demo#1]
Would be nice to have a single jar with all dependencies and manifest entry for main class.
I have implemented this in my fork. (See upcoming pull request)

**Comment by davidef** [comment]
Hi @SvenEwald thanks for your interest but this project is not expected to be used as day-by-day client is just a sample on how to use the library, there no reason why we should build this as a single jar. 
Our internal client implementation include certificate deployment, encrypted certificate storage, automatic renewal, etc but we currently have no plan into make our internal tool opensource.
Furthermore your pull request is a mess with a commit and rollback of the same code.
