### ISSUE TITLE
Missing implementation for local file ChallengeListener

### ISSUE THREAD

**Issue by SvenEwald** [zero11it/acme-client-letsencrypt-demo#3]
The demo can not run on remote machines without (s)ftp. I have implemented a super simple ChallengeListener to create the token files in the local file system. (see upcoming pull request)

**Comment by davidef** [comment]
Hi @SvenEwald thanks for your interest but this project is not expected to be used as day-by-day client is just a sample on how to use the library, feel free to add new challenges to your own client and maybe add a support to automatically deploy the certificate, we have done so in our internal client implementation which include certificate deployment, encrypted certificate storage, automatic renewal, etc but we currently have no plan into make our internal tool opensource.
