### ISSUE TITLE
HOW to user the generate file for nginx ssl???

### ISSUE THREAD

**Issue by lasimmm** [zero11it/acme-client-letsencrypt-demo#5]
hello  HOW to user the generate file for nginx ssl???
![image](https://cloud.githubusercontent.com/assets/3974648/14138391/960e4c82-f69f-11e5-92f9-c7fe04ad4107.png)

.chain.crt
.crt
.csr
.key

help me !!!  

thanks.

**Comment by davidef** [comment]
@lasimmm This project is a demo project on how to use our acme library ( https://github.com/zero11it/acme-client ) is not expected to be a day by day client. Our internal client (based on the same opensource library) works without any issue with both apache and nginx.
