### ISSUE TITLE
How to use a cert

### ISSUE THREAD

**Issue by npomfret** [zero11it/acme-client-letsencrypt-demo#7]
Sorry, this isn't an issue but a question.  I've managed to get a cert (and chain) from letsencrypt and I want to now create an SSLContext object to use in my java web server.  But how?  I've tried many different approaches but can't get it to work.

**Comment by davidef** [comment]
As you said it's not an issue with this project. You'd better ask this on Let's Encrypt community https://community.letsencrypt.org/ or stackoverflow
